apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyc-chat-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kyc-chat-backend
  template:
    metadata:
      labels:
        app: kyc-chat-backend
    spec:
      containers:
        - name: kyc-chat-backend
          image: stanleyotieno/kyc-chat-backend:latest
          ports:
            - containerPort: 8010

---
apiVersion: v1
kind: Service
metadata:
  name: kyc-chat-backend
spec:
  selector:
    app: kyc-chat-backend
  ports:
    - port: 8010
      targetPort: 8010
  type: ClusterIP
