apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-frontend
  labels:
    app:  kyc-report-frontend
spec: 
  replicas: 1
  selector:
    matchLabels:
      app:  kyc-report-frontend
  template:
    metadata:
      labels:
        app:  kyc-report-frontend
    spec:
      containers:
        - name: report-frontend
          image: stanleyotieno/kyc-report-service
          ports:
            - containerPort: 80
          env:
            # Add backend API URL environment variable
            - name: API_BASE_URL
              value: "http://report-service.default.svc.cluster.local:8083"
            # Or if your frontend expects a different env var name, adjust accordingly
            - name: REACT_APP_API_URL
              value: "http://report-service.default.svc.cluster.local:8083"
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 200m
            
---

apiVersion: v1
kind: Service
metadata:
  name: report-frontend
spec:
  type: NodePort
  selector:
    app: kyc-report-frontend
  ports:
  - protocol: TCP
    nodePort: 32070
    port: 80
    targetPort: 80