# Persistent Volume Claim for Report Backend Service
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: report-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: manual
  volumeName: report-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: report-pv
spec:
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/report"
  claimRef:
    namespace: default
    name: report-pvc
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-service
  labels:
    app:  kyc-report-service
spec: 
  replicas: 1
  selector:
    matchLabels:
      app:  kyc-report-service
  template:
    metadata:
      labels:
        app:  kyc-report-service
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command:
            - sh
            - -c
            - >
              until nc -z postgres 5432;
              do
                echo "Waiting for PostgreSQL...";
                sleep 2;
              done
      containers:
        - name: kyc-report-service
          image: stanleyotieno/kyc-backend-report
          ports:
            - containerPort: 8083
          env:
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key:  POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key:  POSTGRES_PASSWORD
          volumeMounts:
            - name: report-storage
              mountPath: /app/data
          resources:
            requests:
              memory: "256Mi"
              cpu: "150m"
            limits:
              memory: "512Mi"
              cpu: "300m"
      volumes:
        - name: report-storage
          persistentVolumeClaim:
            claimName: report-pvc



---
            
apiVersion: v1
kind: Service
metadata:
  name: report-service
spec:
  type: ClusterIP
  selector:
    app: kyc-report-service
  ports:
    - port: 8083
      targetPort: 8083