# --- PVC for persistent storage ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kyc-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  volumeName: kyc-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kyc-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/mnt/data/kyc"
  claimRef:
    name: kyc-pvc
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyc-service-backend
  labels:
    app: kyc-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  kyc-service
  template:
    metadata:
      labels:
        app: kyc-service
    spec:
      containers:
        - name: kyc-service
          image: stanleyotieno/kyc-service-backend
          ports:
            - containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: kyc-service
spec:
  type: ClusterIP
  selector:
    app: kyc-service
  ports:
    - port: 8081
      targetPort: 8081