loki:
  persistence:
    enabled: true
    storageClassName: "local-path"
    accessModes:
      - ReadWriteOnce
    size: 20Gi
  enabled: true
  service:
    type: NodePort
    nodePort: 32009

  yaml:
    auth_enabled: false
    server:
      http_listen_port: 3100

    ingester:
      lifecycler:
        ring:
          kvstore:
            store: inmemory
        final_sleep: 0s
      chunk_idle_period: 5m
      max_chunk_age: 1h
      chunk_target_size: 1048576

    schema_config:
      configs:
        - from: 2022-01-01
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h

    storage_config:
      boltdb_shipper:
        active_index_directory: /loki/index
        cache_location: /loki/cache
        shared_store: filesystem
      filesystem:
        directory: /loki/chunks

    compactor:
      working_directory: /loki/compactor
      shared_store: filesystem
      retention_enabled: true

    limits_config:
      retention_period: 24h

    chunk_store_config:
      max_look_back_period: 24h

    table_manager:
      retention_deletes_enabled: true
      retention_period: 72h

  resources:
    requests:
      memory: 212Mi
      cpu: 100m
    limits:
      memory: 8Gi
      cpu: 200m

promtail:
  enabled: true

grafana:
  enabled: false

  persistence:
    enabled: true
    storageClassName: grafana-pv
